### PR TITLE
Updating settings.xml to point at new Nexus repository

### PR DESCRIPTION
**Pull request by efinlay24**
SONATYPE_USER and SONATYPE_PASSWORD need to be passed in at build time as environment variables.

For more details, see:
http://stackoverflow.com/a/34545644

### CODE REVIEW

**Comment by tosan88** [comment]
Do you plan to create a build in Dockerhub? I'm wondering if we would have to adjust the Dockerfiles which still use the dropwizardbase image from up-registry, at the same time couldn't be migrated to GitHub and get rid of the internal Nexus dependency?

**Comment by efinlay24** [comment]
We'd create a build of `coco/dropwizardbase` in DockerHub.  

All the Dockerfiles that currently point at the old `up-registry.ft.com/coco/dropwizardbase` image will then be updated to pull in the newer `coco/dropwizardbase` image.

However, we'd still continue to push the final built Docker images into the `up-registry`, as I believe we can't make these projects / images public due to closed-source code issues.

**Comment by efinlay24** [comment]
Just as a FYI - this effectively just replaces the old `settings.xml` file that currently points at our old Anthill repositories, which is what's currently being used by anything pulling in the old `up-registry.ft.com/coco/dropwizardbase` image.

**Comment by khatton-ft** [comment]
Do those environment variables persist in the container?

**Comment by efinlay24** [comment]
After a quick test - the environment variables don't persist, but as per the Dockerfile documentation, the credentials are visible in plaintext when the `docker history` command is run against the image:  
https://docs.docker.com/engine/reference/builder/#/arg  

Some additional thoughts on Docker secret management here:  
https://github.com/docker/docker/issues/13490  

Not entirely sure the best way to get around this - we could move the Maven build step outside of the container, then add the final build artifact into the image? That probably presents an entirely new set of problems though.

Will have a chat with Tooling Team to see if they have any ideas (probably not), and raise this in the Tech Forum.

**Comment by efinlay24** [comment]
Turns out that you can `docker inspect` an image as well and just pull out credentials as plaintext. Definitely don't want to be doing this then...

**Comment by efinlay24** [comment]
As discussed in Tech Forum etc - this change is now fine, given that we're migrating our Docker images to the new image registry hosted on our Nexus.

**Pull request merged**
